name: Beta Release

on:
  release:
    types: [published]


jobs:
  build-and-publish-beta:
    # Only run for beta releases
    if: contains(github.event.release.tag_name, '-beta')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun x tsc --noEmit

      - name: Build application
        run: bun run build

      - name: Create Beta Release via Changesets
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run publish-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
