name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Type check
        run: bun x tsc --noEmit
      
      - name: Build application
        run: bun run build
      
      - name: Set package version from release
        run: |
          RELEASE_VERSION=${{ github.event.release.tag_name }}
          # Remove 'v' prefix if present
          VERSION=${RELEASE_VERSION#v}
          # Update version in package.json
          jq ".version = \"$VERSION\"" package.json > package.json.tmp
          mv package.json.tmp package.json
      
      - name: Publish to npm
        run: bun publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
